minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true
strictDepBuilds: true
dangerouslyAllowAllBuilds: false

minimumReleaseAgeExclude:
  - docula@2.0.0

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
