name: release

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: read
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Testing
      run: pnpm test

    - name: Publish
      run: pnpm publish --provenance --access public --no-git-checks

